name: Ahk2Exe
description: GitHub Action to compile AutoHotKey scripts using Ahk2Exe
author: nekocodeX

inputs:
  in:
    description: The path or file name of the AutoHotKey script to compile
    required: true
  out:
    description: The path or file name of the compiled executable (by default, an executable of the same name will be created in the path of the AutoHotKey script specified by the "in" parameter)
    required: false
    default: ''
  icon:
    description: The icon of the executable file is specified
    required: false
    default: ''
  base:
    description: The name of the base file to be used for Ahk2Exe
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Install AutoHotkey
      shell: pwsh
      run: |
        $cwd = (Get-Item .).FullName;
        Invoke-WebRequest "https://www.autohotkey.com/download/ahk.zip" -OutFile "$cwd\autohotkey.zip";
        Expand-Archive -Path "$cwd\autohotkey.zip" -DestinationPath "$cwd\_autohotkey\" -Force;
        Remove-Item -Path "$cwd\autohotkey.zip" -Force
        Write-Output ("$cwd\_autohotkey\;" + "$cwd\_autohotkey\Compiler") | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        if('${{inputs.base}}' -ne ''){
          Write-Output ("BaseFile=$cwd\_autohotkey\Compiler\${{inputs.base}}.bin") | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        }else{
          Copy-Item -Path "$cwd\_autohotkey\Compiler\Unicode 32-bit.bin" -Destination "$cwd\_autohotkey\Compiler\AutoHotkeySC.bin"
        }

    - name: Run Ahk2Exe
      shell: pwsh
      run: |
        $command = 'ahk2exe.exe /silent verbose '
        if('${{inputs.in}}' -ne ''){
          $command += '/in "${{inputs.in}}" '
        }
        if('${{inputs.out}}' -ne ''){
          $command += '/out "${{inputs.out}}" '
        }
        if('${{inputs.icon}}' -ne ''){
          $command += '/icon "${{inputs.icon}}" '
        }
        if('${{inputs.base}}' -ne ''){
          $command += '/base "$Env:BaseFile" '
        }
        $command += "| Write-Output"
        Invoke-Expression $command
        
branding:
  color: green
  icon: terminal
